[package]
name = "elevate"
version = "0.1.0"
authors = ["warren <me@warrenhu.com>"]
edition = "2018"

[dependencies]
winit = "0.18.0"
gfx-hal = "0.1.0"
env_logger = "0.6.0"
log = "0.4.6"
glsl-to-spirv = "0.1.7"
gfx-backend-vulkan = "0.1.0"
